name: Generate Datas

on:
  schedule: # execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualizar datas
    runs-on: ubuntu-latest
    steps:
      # Cria o diretório 'dist'
      - name: Cria o diretório dist
        run: mkdir -p dist

      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: xEvertonWallace
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

